# This class will contain all selectors

class Selectors:
    UserName = "#user-name"
    Password = "#password"
    LoginButton = "#login-button"
    HomePageTitle = ".app_logo"
    ErrorMessage = ".error-message-container.error h3"
    Menu = "#react-burger-menu-btn"
    LogoutButton = "#logout_sidebar_link"
    LoginPageTitle = ".login_logo"
    CartButton = "shopping_cart_link"
    PricesList = ".inventory_item_price"
    SortOption = ".product_sort_container"
    ProductList = ".inventory_item_name"
    AddToCartButton = ".btn.btn_primary.btn_small.btn_inventory"
    CartNumber = ".shopping_cart_badge"
    RemoveFromCartButton = ".btn.btn_secondary.btn_small.btn_inventory"
    Cart = "shopping_cart_link"
    Checkout = "checkout"
    FirstName = "first-name"
    LastName = "last-name"
    ZipCode = "postal-code"
    ContinueButton = "continue"
    FinishButton = "finish"
    CheckoutBanner = "complete-header"
    ResetApp = "reset_sidebar_link"
    CloseMenu = "react-burger-cross-btn"
    TotalPriceBeforeTax = "summary_subtotal_label"
    TotalPriceAfterTax = "summary_info_label.summary_total_label"
    MainPage = "inventory_sidebar_link"
